### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by djsd123**
[Jira Ticket](https://collaborate2.ons.gov.uk/jira/browse/CATDDSC-26)

- Create a project
- Create a state bucket
- Enable APIs
- Set `deletion_protection` to `true` for formal projects

### CODE REVIEW

**Comment by djsd123** [comment]
Thinking of moving  this to [ONS-Terraform](https://github.com/ONSdigital/ons-terraform/tree/master/terraform/gcp)?

**Review by kierenbeckett — APPROVED** [review]

**Comment by kierenbeckett** [comment]
As discussed, I think we should try to avoid collecting too much terraform in one place, both in terms of too much code in a single repo with multiple owners and also in terms of having too many resources in the same terraform state (makes it slow, increases blast radius).  I wouldn't put this in ons-terraform and maybe this repo should be named to be specific to this module, or all the data science project modules.

**Comment by kierenbeckett** [comment]
Also as discussed, If we don't create all the instances of this module as part of the ons-terraform state, we have a couple of other options:
* Have a 'data science projects' state
* Have a state per data science project instance, following a similar pattern to how we make instances of the k8 project module at ONSdigital/gke-terraform

**Comment by djsd123** [comment]
@kierenbeckett Agreed with both points.  Ideally a state per project feels safer, so we'll aim for that and hope it scales.

**Pull request merged**
